<?php
/**
 * Bảng dịch tên bệnh Tây Y sang tiếng Việt
 * Định dạng: 'English name' => 'Tên Tiếng Việt'
 * Nếu không có trong bảng, hiển thị nguyên bản tiếng Anh
 */
function translateDisease(string $en): string
{
    static $map = null;
    if ($map === null) {
        $map = getDiseaseMap();
    }
    return $map[$en] ?? $en;
}

/**
 * Hiển thị "Tên Việt (English)" hoặc chỉ tên Việt nếu không cần
 */
function displayDisease(string $en): string
{
    static $map = null;
    if ($map === null) {
        $map = getDiseaseMap();
    }
    if (isset($map[$en])) {
        $vi = $map[$en];
        // Nếu tên Việt đã có ký hiệu tắt trong ngoặc → không thêm nữa
        if (strpos($vi, '(') !== false) {
            return $vi;
        }
        // Nếu tên Việt đã chứa tên Anh (hoặc ngược lại) → không lặp
        if (mb_stripos($vi, $en, 0, 'UTF-8') !== false) {
            return $vi;
        }
        // Thêm tên Anh vào ngoặc để bác sĩ tham khảo
        return $vi . ' (' . $en . ')';
    }
    // Không tìm thấy dịch → hiển thị nguyên tiếng Anh
    return $en;
}

function getDiseaseMap(): array
{
    return [
        // === TIM MẠCH ===
        'Essential hypertension'                    => 'Tăng huyết áp vô căn',
        'Hypertension'                              => 'Tăng huyết áp',
        'Hypertensive crisis'                       => 'Cơn tăng huyết áp nguy kịch',
        'Hypertensive urgency'                      => 'Tăng huyết áp khẩn cấp',
        'Hypertensive headache'                     => 'Đau đầu do tăng huyết áp',
        'Hypertensive nephropathy'                  => 'Bệnh thận do tăng huyết áp',
        'Hypertension with yin deficiency'          => 'Tăng huyết áp thể Âm hư',
        'Coronary artery disease'                   => 'Bệnh mạch vành',
        'Coronary artery disease stable angina'     => 'Bệnh mạch vành - đau thắt ngực ổn định',
        'Angina pectoris'                           => 'Đau thắt ngực',
        'Unstable angina'                           => 'Đau thắt ngực không ổn định',
        'Microvascular angina'                      => 'Đau thắt ngực vi mạch',
        'Stable angina with obesity/metabolic syndrome' => 'Đau thắt ngực ổn định kèm béo phì/hội chứng chuyển hóa',
        'Acute Coronary Syndrome (ACS)'             => 'Hội chứng mạch vành cấp (ACS)',
        'Acute myocardial infarction'               => 'Nhồi máu cơ tim cấp',
        'STEMI / NSTEMI'                            => 'Nhồi máu cơ tim ST chênh/không ST chênh',
        'Post-MI'                                   => 'Sau nhồi máu cơ tim',
        'Post-MI recovery'                          => 'Phục hồi sau nhồi máu cơ tim',
        'Heart failure'                             => 'Suy tim',
        'Heart failure (right-sided)'               => 'Suy tim phải',
        'Heart failure with reduced EF'             => 'Suy tim phân suất tống máu giảm',
        'Heart failure with reduced EF (HFrEF)'     => 'Suy tim HFrEF',
        'Mild heart failure (HFpEF)'                => 'Suy tim nhẹ HFpEF',
        'Congestive heart failure with pulmonary congestion' => 'Suy tim sung huyết có ứ máu phổi',
        'Cardiac asthma differential'               => 'Hen tim (cần phân biệt)',
        'Cardiogenic shock mild'                    => 'Sốc tim nhẹ',
        'Atrial fibrillation'                       => 'Rung nhĩ',
        'Cardiac arrhythmia mild (PSVT, PVC)'       => 'Loạn nhịp tim nhẹ (PSVT, ngoại tâm thu thất)',
        'Complete heart block'                      => 'Block nhĩ thất hoàn toàn',
        'Sick sinus syndrome'                       => 'Hội chứng nút xoang bệnh lý',
        'Aortic dissection Type A'                  => 'Bóc tách động mạch chủ type A',
        'Pulmonary hypertension mild'               => 'Tăng áp phổi nhẹ',
        'Pulmonary hypertension with right heart failure' => 'Tăng áp phổi kèm suy tim phải',
        'Peripheral vascular disease'               => 'Bệnh mạch máu ngoại biên',
        'Peripheral vascular disease with malnutrition' => 'Bệnh mạch máu ngoại biên kèm suy dinh dưỡng',
        'Thromboangiitis obliterans'                => 'Viêm tắc động mạch huyết khối',
        'Thrombophilia'                             => 'Rối loạn đông máu dễ tắc mạch',
        'DIC (disseminated intravascular coagulation)' => 'Đông máu nội mạch rải rác (DIC)',
        'Raynaud phenomenon'                        => 'Hội chứng Raynaud',
        "Raynaud's phenomenon"                      => 'Hội chứng Raynaud',

        // === THẦN KINH / TÂM THẦN ===
        'Migraine'                                  => 'Đau đầu Migraine',
        'Tension headache'                          => 'Đau đầu căng thẳng',
        'Tension-type headache (vertex)'            => 'Đau đầu căng thẳng vùng đỉnh',
        'Tension headache with irritability'        => 'Đau đầu căng thẳng kèm dễ cáu',
        'Cervicogenic headache'                     => 'Đau đầu do cổ',
        'Anemia headache'                           => 'Đau đầu do thiếu máu',
        'Common cold with headache'                 => 'Cảm lạnh kèm đau đầu',
        'Obesity-related headache'                  => 'Đau đầu do béo phì',
        'Post-hemorrhage headache'                  => 'Đau đầu sau mất máu',
        'Postpartum headache'                       => 'Đau đầu sau sinh',
        'Vestibular migraine'                       => 'Migraine tiền đình',
        'Benign paroxysmal positional vertigo'      => 'Chóng mặt lành tính tư thế (BPPV)',
        'Meniere disease'                           => 'Bệnh Meniere',
        'Vertebrobasilar insufficiency'             => 'Thiếu máu nền sọ não',
        'Pre-stroke state'                          => 'Tiền đột quỵ',
        'Early stroke'                              => 'Đột quỵ sớm',
        'TIA'                                       => 'Cơn thiếu máu não thoáng qua (TIA)',
        'TIA (Transient Ischemic Attack)'           => 'Cơn thiếu máu não thoáng qua (TIA)',
        'Cerebrovascular disease'                   => 'Bệnh mạch máu não',
        'Ischemic stroke (pre-stroke)'              => 'Đột quỵ thiếu máu (giai đoạn tiền)',
        'Post-stroke sequelae'                      => 'Di chứng sau đột quỵ',
        'Post-stroke cognitive impairment'          => 'Suy giảm nhận thức sau đột quỵ',
        'Post-stroke rehabilitation'                => 'Phục hồi chức năng sau đột quỵ',
        'Vascular dementia'                         => 'Sa sút trí tuệ mạch máu',
        'Dementia'                                  => 'Sa sút trí tuệ',
        'Dementia mild-moderate'                    => 'Sa sút trí tuệ mức nhẹ-vừa',
        "Alzheimer's disease early-moderate"        => 'Bệnh Alzheimer giai đoạn sớm-vừa',
        "Parkinson's disease early"                 => 'Bệnh Parkinson giai đoạn sớm',
        'Parkinson disease (early)'                 => 'Bệnh Parkinson giai đoạn sớm',
        "Parkinson's with dementia"                 => 'Bệnh Parkinson kèm sa sút trí tuệ',
        'Essential tremor'                          => 'Run vô căn',
        'Epilepsy (absence)'                        => 'Động kinh thể vắng ý thức',
        'Epilepsy absence type'                     => 'Động kinh thể vắng ý thức',
        'Encephalitis'                              => 'Viêm não',
        'Encephalitis agitation'                    => 'Viêm não kèm kích động',
        'Bacterial meningitis'                      => 'Viêm màng não vi khuẩn',
        'Meningococcemia'                           => 'Nhiễm khuẩn não mô cầu',
        'Multiple sclerosis'                        => 'Xơ cứng rải rác',
        'Multiple sclerosis mild'                   => 'Xơ cứng rải rác nhẹ',
        'Peripheral neuropathy'                     => 'Bệnh thần kinh ngoại biên',
        'Restless leg syndrome'                     => 'Hội chứng chân không yên',
        'Nocturnal leg cramps'                      => 'Vọp bẻ (chuột rút) ban đêm',
        'Autonomic dysfunction'                     => 'Rối loạn thần kinh thực vật',
        'Autonomic nervous dysfunction'             => 'Rối loạn thần kinh thực vật',
        'Orthostatic hypotension'                   => 'Hạ huyết áp tư thế',
        'Neurasthenia'                              => 'Suy nhược thần kinh',
        'Neurasthenia ICD-10 F48'                   => 'Suy nhược thần kinh (F48)',
        'Neurosis'                                  => 'Rối loạn tâm căn',
        'Anxiety disorder'                          => 'Rối loạn lo âu',
        'Anxiety disorder GI'                       => 'Rối loạn lo âu kèm triệu chứng tiêu hóa',
        'Anxiety disorder with GI symptoms'         => 'Rối loạn lo âu có triệu chứng tiêu hóa',
        'Anxiety disorder with insomnia'            => 'Rối loạn lo âu kèm mất ngủ',
        'Anxiety disorder with somatic complaints'  => 'Rối loạn lo âu kèm triệu chứng cơ thể',
        'Anxiety with insomnia'                     => 'Lo âu kèm mất ngủ',
        'Anxiety with irritability'                 => 'Lo âu kèm dễ cáu',
        'Anxiety-related GI disorder'               => 'Rối loạn tiêu hóa do lo âu',
        'Generalized anxiety disorder'              => 'Rối loạn lo âu lan tỏa',
        'Social anxiety disorder'                   => 'Rối loạn lo âu xã hội',
        'Acute anxiety attack'                      => 'Cơn lo âu cấp tính',
        'Acute anxiety/agitation'                   => 'Lo âu/kích động cấp tính',
        'Panic disorder mild'                       => 'Rối loạn hoảng sợ nhẹ',
        'Depression'                                => 'Trầm cảm',
        'Depression with fatigue'                   => 'Trầm cảm kèm mệt mỏi',
        'Depression with psychomotor retardation'   => 'Trầm cảm kèm chậm vận động tâm thần',
        'Depression with psychotic features'        => 'Trầm cảm có loạn thần',
        'Major depressive disorder mild-moderate'   => 'Rối loạn trầm cảm chủ yếu mức nhẹ-vừa',
        'Chronic fatigue with depression'           => 'Mệt mỏi mạn tính kèm trầm cảm',
        'Adjustment disorder'                       => 'Rối loạn thích nghi',
        'Adjustment disorder with anxiety'          => 'Rối loạn thích nghi kèm lo âu',
        'Bipolar disorder (manic phase)'            => 'Rối loạn lưỡng cực (pha hưng cảm)',
        'Bipolar disorder manic phase'              => 'Rối loạn lưỡng cực pha hưng cảm',
        'Bipolar disorder mild'                     => 'Rối loạn lưỡng cực nhẹ',
        'Schizophrenia (undifferentiated)'          => 'Tâm thần phân liệt (không biệt định)',
        'Schizophrenia acute psychosis'             => 'Tâm thần phân liệt giai đoạn loạn thần cấp',
        'Schizophrenia negative symptoms'           => 'Tâm thần phân liệt triệu chứng âm tính',
        'Acute psychosis'                           => 'Loạn thần cấp',
        'Drug-induced psychosis'                    => 'Loạn thần do thuốc',
        'Insomnia'                                  => 'Mất ngủ',
        'Insomnia primary'                          => 'Mất ngủ nguyên phát',
        'Insomnia with autonomic dysfunction'       => 'Mất ngủ kèm rối loạn thần kinh thực vật',
        'Menopausal insomnia'                       => 'Mất ngủ thời kỳ mãn kinh',
        'Anxiety with insomnia'                     => 'Lo âu kèm mất ngủ',
        'Chronic stress'                            => 'Stress mạn tính',
        'Burnout syndrome'                          => 'Hội chứng kiệt sức (Burnout)',
        'PTSD mild'                                 => 'Rối loạn stress sau sang chấn nhẹ (PTSD)',
        'PTSD with nightmares'                      => 'PTSD kèm ác mộng',
        'Delirium tremens'                          => 'Sảng rượu',
        'Cognitive decline'                         => 'Suy giảm nhận thức',
        'Age-related cognitive decline'             => 'Suy giảm nhận thức theo tuổi',
        'Mild cognitive impairment (MCI)'           => 'Suy giảm nhận thức nhẹ (MCI)',
        'Febrile convulsions in children'           => 'Co giật do sốt ở trẻ em',

        // === HÔ HẤP ===
        'Common cold (rhinovirus)'                  => 'Cảm lạnh thông thường (rhinovirus)',
        'Acute upper respiratory infection'         => 'Viêm hô hấp trên cấp',
        'Acute upper respiratory infection (common cold)' => 'Viêm hô hấp trên cấp (cảm lạnh)',
        'Viral upper respiratory infection'         => 'Viêm hô hấp trên do virus',
        'Recurrent upper respiratory infections'    => 'Viêm hô hấp trên tái phát',
        'Influenza'                                 => 'Cúm',
        'Influenza (early stage)'                   => 'Cúm giai đoạn đầu',
        'Influenza early stage'                     => 'Cúm giai đoạn đầu',
        'Autumn/dry season upper respiratory infection' => 'Viêm hô hấp trên mùa thu/khô',
        'Air-conditioned environment syndrome'      => 'Hội chứng phòng điều hòa',
        'Allergic rhinitis'                         => 'Viêm mũi dị ứng',
        'Allergic rhinitis cold exposure'           => 'Viêm mũi dị ứng do lạnh',
        'Chronic pharyngitis'                       => 'Viêm họng mạn tính',
        'Acute tonsillitis'                         => 'Viêm amidan cấp',
        'Acute tonsillitis / pharyngitis'           => 'Viêm amidan/họng cấp',
        'Streptococcal pharyngitis'                 => 'Viêm họng liên cầu',
        'Laryngitis dry type'                       => 'Viêm thanh quản thể khô',
        'Upper airway cough syndrome'               => 'Hội chứng ho đường hô hấp trên',
        'Asthma (atopic)'                           => 'Hen phế quản thể dị ứng',
        'Asthma chronic'                            => 'Hen phế quản mạn tính',
        'Asthma in remission'                       => 'Hen phế quản giai đoạn ổn định',
        'Asthma phlegm type'                        => 'Hen phế quản thể đàm',
        'Asthma with excessive phlegm'              => 'Hen phế quản nhiều đàm',
        'Bronchial asthma (cold type)'              => 'Hen phế quản thể hàn',
        'Bronchial asthma cold-triggered'           => 'Hen phế quản khởi phát do lạnh',
        'Cough variant asthma triggered by stress'  => 'Hen biến thể ho khởi phát do stress',
        'Psychosomatic cough'                       => 'Ho tâm lý',
        'Drug-induced cough (ACE inhibitors)'       => 'Ho do thuốc ức chế ACE',
        'Dry cough (post-infectious)'               => 'Ho khan sau nhiễm khuẩn',
        'Dry cough post-URI'                        => 'Ho khan sau viêm hô hấp trên',
        'Autumn bronchitis'                         => 'Viêm phế quản mùa thu',
        'Acute bronchitis bacterial'                => 'Viêm phế quản cấp do vi khuẩn',
        'Acute bronchitis cold type'                => 'Viêm phế quản cấp thể hàn',
        'Acute bronchitis dry'                      => 'Viêm phế quản cấp thể khô',
        'Acute bronchitis heat type'                => 'Viêm phế quản cấp thể nhiệt',
        'Chronic bronchitis'                        => 'Viêm phế quản mạn tính',
        'Chronic bronchitis dry type'               => 'Viêm phế quản mạn tính thể khô',
        'Chronic bronchitis winter exacerbation'    => 'Viêm phế quản mạn tính đợt cấp mùa đông',
        'Chronic bronchitis with excessive mucus'   => 'Viêm phế quản mạn tính nhiều đàm',
        'Smoker\'s cough early'                     => 'Ho do hút thuốc giai đoạn sớm',
        'Bronchiectasis'                            => 'Giãn phế quản',
        'Bronchiectasis infective exacerbation'     => 'Giãn phế quản đợt nhiễm khuẩn',
        'Bronchiectasis stable'                     => 'Giãn phế quản giai đoạn ổn định',
        'Bronchiectasis with infection'             => 'Giãn phế quản kèm nhiễm khuẩn',
        'Post-infectious bronchial hypersecretion'  => 'Tăng tiết phế quản sau nhiễm khuẩn',
        'COPD'                                      => 'Bệnh phổi tắc nghẽn mạn tính (COPD)',
        'COPD GOLD III-IV'                          => 'COPD mức độ nặng-rất nặng (GOLD III-IV)',
        'COPD cold type acute exacerbation'         => 'COPD đợt cấp thể hàn',
        'COPD exacerbation'                         => 'COPD đợt cấp',
        'COPD mild (GOLD I-II)'                     => 'COPD nhẹ-vừa (GOLD I-II)',
        'COPD moderate type'                        => 'COPD mức vừa',
        'COPD with cor pulmonale'                   => 'COPD kèm tâm phế mạn',
        'Acute exacerbation COPD'                   => 'COPD đợt cấp',
        'Chronic respiratory failure'               => 'Suy hô hấp mạn tính',
        'Community-acquired pneumonia (CAP)'        => 'Viêm phổi mắc tại cộng đồng (CAP)',
        'Hospital-acquired pneumonia'               => 'Viêm phổi bệnh viện',
        'Aspiration pneumonia'                      => 'Viêm phổi hít',
        'Early pneumonia'                           => 'Viêm phổi giai đoạn sớm',
        'COVID-19 (mild)'                           => 'COVID-19 (nhẹ)',
        'COVID-19 mild-moderate respiratory symptoms' => 'COVID-19 triệu chứng hô hấp nhẹ-vừa',
        'COVID-19 pneumonia moderate-severe'        => 'Viêm phổi COVID-19 vừa-nặng',
        'Post-COVID dry cough'                      => 'Ho khan hậu COVID',
        'Post-COVID cardiac-pulmonary syndrome'     => 'Hội chứng tim-phổi hậu COVID',
        'Post-COVID pulmonary sequelae'             => 'Di chứng phổi hậu COVID',
        'Post-COVID-19 syndrome'                    => 'Hội chứng hậu COVID-19',
        'Pulmonary tuberculosis'                    => 'Lao phổi',
        'Pulmonary TB (post-active, residual)'      => 'Lao phổi (giai đoạn ổn định, tồn dư)',
        'Pulmonary TB active hemoptysis'            => 'Lao phổi hoạt động - ho ra máu',
        'Post-TB fibrosis'                          => 'Xơ phổi sau lao',
        'Post-TB sequelae'                          => 'Di chứng lao phổi',
        'Pulmonary fibrosis'                        => 'Xơ phổi',
        'Interstitial lung disease'                 => 'Bệnh phổi mô kẽ',
        'Interstitial lung disease mild'            => 'Bệnh phổi mô kẽ nhẹ',
        'Pulmonary embolism hemoptysis'             => 'Thuyên tắc phổi - ho ra máu',
        'Mitral stenosis hemoptysis'                => 'Hẹp van hai lá - ho ra máu',
        'Hemoptysis from bronchiectasis'            => 'Ho ra máu do giãn phế quản',
        'Lung cancer (NSCLC, SCLC)'                 => 'Ung thư phổi (NSCLC, SCLC)',
        'Lung cancer hemoptysis'                    => 'Ung thư phổi - ho ra máu',
        'Pulmonary metastasis'                      => 'Di căn phổi',
        'Benign lung nodule (hamartoma, granuloma)' => 'Nốt phổi lành tính (hamartoma, u hạt)',
        'Post-radiation pneumonitis'                => 'Viêm phổi sau xạ trị',
        'Pertussis early stage'                     => 'Ho gà giai đoạn đầu',
        'Dry eye syndrome'                          => 'Hội chứng khô mắt',

        // === TIÊU HÓA ===
        'GERD'                                      => 'Trào ngược dạ dày-thực quản (GERD)',
        'GERD chronic'                              => 'GERD mạn tính',
        'GERD cough with emotional component'       => 'GERD gây ho kèm yếu tố cảm xúc',
        'GERD dry cough differential'               => 'GERD gây ho khan (cần phân biệt)',
        'GERD mimicking angina'                     => 'GERD giả đau thắt ngực',
        'GERD stress-induced'                       => 'GERD do stress',
        'GERD with emotional component'             => 'GERD kèm yếu tố cảm xúc',
        'Esophagitis'                               => 'Viêm thực quản',
        'Hiatal hernia'                             => 'Thoát vị khe hoành',
        'Acute gastritis'                           => 'Viêm dạ dày cấp',
        'Chronic atrophic gastritis'                => 'Viêm dạ dày teo mạn tính',
        'Chronic gastric ulcer'                     => 'Loét dạ dày mạn tính',
        'Chronic gastritis atrophic'                => 'Viêm dạ dày teo mạn tính',
        'Helicobacter pylori gastritis'             => 'Viêm dạ dày do H. pylori',
        'Post-H.pylori eradication therapy'         => 'Sau điều trị tiệt trừ H. pylori',
        'Gastritis'                                 => 'Viêm dạ dày',
        'Gastritis erosive'                         => 'Viêm dạ dày ăn mòn',
        'Peptic ulcer'                              => 'Loét dạ dày-tá tràng',
        'Peptic ulcer disease'                      => 'Bệnh loét dạ dày-tá tràng',
        'Peptic ulcer stress-related'               => 'Loét dạ dày do stress',
        'Gastric spasm'                             => 'Co thắt dạ dày',
        'Gastric ulcer'                             => 'Loét dạ dày',
        'Gastroparesis'                             => 'Liệt dạ dày',
        'Gastroparesis mild'                        => 'Liệt dạ dày nhẹ',
        'Gastroparesis post-meal'                   => 'Liệt dạ dày sau ăn',
        'Post-gastrectomy syndrome'                 => 'Hội chứng sau cắt dạ dày',
        'Functional dyspepsia'                      => 'Khó tiêu chức năng',
        'Functional dyspepsia post-prandial distress' => 'Khó tiêu chức năng sau ăn',
        'Non-ulcer dyspepsia'                       => 'Khó tiêu không do loét',
        'Functional epigastric pain syndrome'       => 'Đau thượng vị chức năng',
        'Dyspepsia'                                 => 'Khó tiêu',
        'Acute indigestion'                         => 'Khó tiêu cấp',
        'Nervous vomiting'                          => 'Nôn ói do thần kinh',
        'Chemotherapy-induced nausea'               => 'Buồn nôn do hóa trị',
        'Epigastric pain with vomiting (vagal)'     => 'Đau thượng vị kèm nôn (phế vị)',
        'Hyperemesis'                               => 'Nôn ói nặng',
        'Post-operative nausea'                     => 'Buồn nôn sau phẫu thuật',
        'Hiccup intractable'                        => 'Nấc cụt dai dẳng',
        'IBS'                                       => 'Hội chứng ruột kích thích (IBS)',
        'IBS mixed'                                 => 'Hội chứng ruột kích thích thể hỗn hợp',
        'IBS with anxiety'                          => 'Hội chứng ruột kích thích kèm lo âu',
        'IBS with low-grade inflammation'           => 'IBS kèm viêm nhẹ',
        'IBS-C'                                     => 'Hội chứng ruột kích thích táo bón (IBS-C)',
        'IBS-D'                                     => 'Hội chứng ruột kích thích tiêu chảy (IBS-D)',
        'IBS-D (Irritable Bowel Syndrome - Diarrhea predominant)' => 'Hội chứng ruột kích thích thể tiêu chảy (IBS-D)',
        'IBS-D elderly'                             => 'IBS-D ở người cao tuổi',
        'Irritable bowel syndrome'                  => 'Hội chứng ruột kích thích',
        'Irritable bowel syndrome - constipation predominant (IBS-C)' => 'Hội chứng ruột kích thích thể táo bón (IBS-C)',
        'Functional diarrhea'                       => 'Tiêu chảy chức năng',
        'Functional abdominal pain'                 => 'Đau bụng chức năng',
        'Functional constipation'                   => 'Táo bón chức năng',
        'Chronic diarrhea'                          => 'Tiêu chảy mạn tính',
        'Chronic diarrhea IBS-D elderly'            => 'Tiêu chảy mạn tính IBS-D người cao tuổi',
        'Stress-induced diarrhea'                   => 'Tiêu chảy do stress',
        'Chronic non-infectious diarrhea'           => 'Tiêu chảy mạn tính không do nhiễm khuẩn',
        'Acute gastroenteritis'                     => 'Viêm dạ dày ruột cấp',
        'Acute gastroenteritis (summer)'            => 'Viêm dạ dày ruột cấp (mùa hè)',
        'Infectious gastroenteritis'                => 'Viêm dạ dày ruột nhiễm khuẩn',
        'Chronic gastroenteritis'                   => 'Viêm dạ dày ruột mạn tính',
        'Acute bacterial dysentery'                 => 'Lỵ vi khuẩn cấp',
        'Amebic dysentery'                          => 'Lỵ amip',
        'Giardiasis'                                => 'Nhiễm ký sinh trùng Giardia',
        'Campylobacter/Salmonella enteritis'        => 'Viêm ruột do Campylobacter/Salmonella',
        'Food poisoning (summer)'                   => 'Ngộ độc thực phẩm (mùa hè)',
        'Traveler\'s diarrhea'                      => 'Tiêu chảy du lịch',
        'Constipation acute'                        => 'Táo bón cấp',
        'Constipation functional'                   => 'Táo bón chức năng',
        'Elderly constipation'                      => 'Táo bón người cao tuổi',
        'Drug-induced constipation (opioids)'       => 'Táo bón do thuốc (opioid)',
        'Opioid-induced constipation'               => 'Táo bón do thuốc opioid',
        'Post-febrile constipation'                 => 'Táo bón sau sốt',
        'Post-surgical constipation'                => 'Táo bón sau phẫu thuật',
        'Post-surgical ileus resolving'             => 'Tắc ruột sau phẫu thuật đang hồi phục',
        'Gastrointestinal bleeding chronic low-grade' => 'Xuất huyết tiêu hóa mạn tính mức độ nhẹ',
        'Hematemesis'                               => 'Nôn ra máu',
        'Rectal prolapse'                           => 'Sa trực tràng',
        'Fecal incontinence'                        => 'Đại tiện không tự chủ',
        'Fecal incontinence elderly'                => 'Đại tiện không tự chủ ở người cao tuổi',
        'Crohn\'s disease mild'                     => 'Bệnh Crohn nhẹ',
        'Ulcerative colitis flare'                  => 'Viêm loét đại tràng đợt cấp',
        'Inflammatory bowel disease'                => 'Bệnh viêm ruột',
        'Microscopic colitis'                       => 'Viêm đại tràng vi thể',
        'Celiac disease'                            => 'Bệnh Celiac',
        'Malabsorption'                             => 'Kém hấp thu',
        'Malabsorption elderly'                     => 'Kém hấp thu ở người cao tuổi',
        'Malnutrition'                              => 'Suy dinh dưỡng',
        'Hepatitis (acute)'                         => 'Viêm gan cấp',
        'Hepatitis A/E'                             => 'Viêm gan A/E',
        'Acute hepatitis'                           => 'Viêm gan cấp',
        'Chronic hepatitis'                         => 'Viêm gan mạn tính',
        'Chronic hepatitis B/C'                     => 'Viêm gan B/C mạn tính',
        'Chronic hepatitis with depression'         => 'Viêm gan mạn tính kèm trầm cảm',
        'Chronic hepatitis with fatigue and depression' => 'Viêm gan mạn tính kèm mệt mỏi và trầm cảm',
        'NAFLD'                                     => 'Gan nhiễm mỡ không do rượu (NAFLD)',
        'Hepatocellular carcinoma (early)'          => 'Ung thư tế bào gan (giai đoạn sớm)',
        'Liver cirrhosis'                           => 'Xơ gan',
        'Cirrhosis portal hypertension'             => 'Xơ gan tăng áp cửa',
        'Cirrhosis with ascites'                    => 'Xơ gan có cổ trướng',
        'Hepatosplenomegaly'                        => 'Gan lách to',
        'Portal hypertension'                       => 'Tăng áp tĩnh mạch cửa',
        'Cholecystitis'                             => 'Viêm túi mật',
        'Cholelithiasis'                            => 'Sỏi mật',
        'Cholangitis'                               => 'Viêm đường mật',

        // === THẬN / TIẾT NIỆU ===
        'UTI'                                       => 'Nhiễm trùng đường tiểu (UTI)',
        'Urinary tract infection'                   => 'Nhiễm trùng đường tiểu',
        'Recurrent UTI'                             => 'Nhiễm trùng tiểu tái phát',
        'Diabetic patient with recurrent UTI'       => 'Bệnh nhân đái tháo đường viêm đường tiểu tái phát',
        'Interstitial cystitis'                     => 'Viêm bàng quang kẽ',
        'Chronic pyelonephritis'                    => 'Viêm bể thận mạn tính',
        'IgA nephropathy'                           => 'Bệnh thận IgA',
        'Lupus nephritis maintenance'               => 'Viêm thận lupus giai đoạn duy trì',
        'Diabetic nephropathy'                      => 'Bệnh thận đái tháo đường',
        'Hypertensive nephropathy'                  => 'Bệnh thận do tăng huyết áp',
        'Chronic kidney disease mild'               => 'Bệnh thận mạn giai đoạn nhẹ',
        'Chronic kidney disease stage 3-5'          => 'Bệnh thận mạn giai đoạn 3-5',
        'Chronic kidney disease with edema'         => 'Bệnh thận mạn kèm phù',
        'CKD advanced'                              => 'Bệnh thận mạn giai đoạn tiến triển',
        'CKD with edema'                            => 'Bệnh thận mạn kèm phù',
        'CKD with recurrent infections'             => 'Bệnh thận mạn kèm nhiễm khuẩn tái phát',
        'Early CKD'                                 => 'Bệnh thận mạn giai đoạn sớm',
        'Late-stage chronic kidney disease'         => 'Bệnh thận mạn giai đoạn cuối',
        'Chronic renal disease early'               => 'Bệnh thận mạn giai đoạn sớm',
        'Nephrotic syndrome'                        => 'Hội chứng thận hư',
        'Nocturia'                                  => 'Tiểu đêm',
        'Overactive bladder'                        => 'Bàng quang tăng hoạt',
        'Urinary incontinence'                      => 'Tiểu không tự chủ',
        'Stress urinary incontinence'               => 'Tiểu không tự chủ khi gắng sức',
        'BPH with nocturia'                         => 'Phì đại tiền liệt tuyến kèm tiểu đêm',
        'Benign prostatic hyperplasia'              => 'Phì đại tiền liệt tuyến lành tính',
        'Benign prostatic hyperplasia mild'         => 'Phì đại tiền liệt tuyến nhẹ',
        'Nephrotic syndrome'                        => 'Hội chứng thận hư',

        // === CƠ XƯƠNG KHỚP ===
        'Osteoarthritis (cold climate aggravated)'  => 'Thoái hóa khớp (nặng hơn do lạnh)',
        'Osteoarthritis (humidity aggravated)'      => 'Thoái hóa khớp (nặng hơn do ẩm)',
        'Osteoarthritis cold weather exacerbation'  => 'Thoái hóa khớp đợt cấp do lạnh',
        'Rheumatoid arthritis'                      => 'Viêm khớp dạng thấp',
        'Rheumatoid arthritis (active)'             => 'Viêm khớp dạng thấp giai đoạn hoạt động',
        'Rheumatoid arthritis (early)'              => 'Viêm khớp dạng thấp giai đoạn sớm',
        'Rheumatoid arthritis cold stage'           => 'Viêm khớp dạng thấp thể hàn',
        'Rheumatoid arthritis flare'                => 'Viêm khớp dạng thấp đợt bùng phát',
        'Gout'                                      => 'Gút',
        'Gout (acute attack)'                       => 'Gút cơn cấp',
        'Gout (cold trigger)'                       => 'Gút khởi phát do lạnh',
        'Gout inter-attack'                         => 'Gút giai đoạn giữa các cơn',
        'Acute gout arthritis'                      => 'Viêm khớp gút cấp',
        'Pseudogout'                                => 'Giả gút (lắng đọng canxi)',
        'Bursitis'                                  => 'Viêm túi dịch khớp',
        'Septic arthritis (must exclude)'           => 'Viêm khớp nhiễm khuẩn (cần loại trừ)',
        'Viral arthritis'                           => 'Viêm khớp do virus',
        'Reactive arthritis'                        => 'Viêm khớp phản ứng',
        'Palindromic rheumatism'                    => 'Thấp khớp palindromic',
        'Fibromyalgia'                              => 'Đau cơ xơ hóa',
        'Lumbar disc herniation'                    => 'Thoát vị đĩa đệm thắt lưng',
        'Lumbar spondylosis'                        => 'Thoái hóa cột sống thắt lưng',
        'Osteoporosis'                              => 'Loãng xương',
        'Osteopenia'                                => 'Thiếu xương (tiền loãng xương)',
        'Post-menopausal bone loss'                 => 'Mất xương sau mãn kinh',
        'Pathological fractures'                    => 'Gãy xương bệnh lý',
        'Chronic pain syndrome'                     => 'Hội chứng đau mạn tính',
        'Chronic pain syndromes'                    => 'Các hội chứng đau mạn tính',
        'Post-traumatic pain'                       => 'Đau sau chấn thương',
        'Sarcopenia'                                => 'Suy giảm khối cơ (Sarcopenia)',
        'Nocturnal leg cramps'                      => 'Chuột rút chân ban đêm',
        'Scleroderma'                               => 'Xơ cứng bì',

        // === NỘI TIẾT / CHUYỂN HÓA ===
        'Diabetes mellitus (advanced)'              => 'Đái tháo đường (giai đoạn nặng)',
        'Diabetes mellitus type 2 (Tỳ âm hư thể)'  => 'Đái tháo đường type 2 (thể Tỳ âm hư)',
        'Hyperlipidemia'                            => 'Rối loạn lipid máu',
        'Hyperlipidemia with CAD'                   => 'Rối loạn lipid máu kèm bệnh mạch vành',
        'Metabolic syndrome'                        => 'Hội chứng chuyển hóa',
        'Obesity'                                   => 'Béo phì',
        'Hypothyroidism'                            => 'Suy giáp',
        'Hypothyroidism with cardiac involvement'   => 'Suy giáp kèm ảnh hưởng tim',
        'Hypothyroidism with hot flushes'           => 'Suy giáp kèm bốc hỏa',
        'Hypothyroidism with myxedema'              => 'Suy giáp phù niêm',
        'Congenital hypothyroidism'                 => 'Suy giáp bẩm sinh',
        'Hyperthyroidism mild'                      => 'Cường giáp nhẹ',
        'Hyperthyroidism with tremor'               => 'Cường giáp kèm run',
        'Subacute thyroiditis'                      => 'Viêm giáp bán cấp',
        'Thyroid disorders mixed'                   => 'Bệnh tuyến giáp hỗn hợp',
        'Thyroid nodules'                           => 'Nhân giáp',
        'Adrenal fatigue'                           => 'Mệt mỏi tuyến thượng thận',
        'Adrenal insufficiency'                     => 'Suy thượng thận',
        'Severe hypothalamic-pituitary dysfunction' => 'Rối loạn vùng dưới đồi-tuyến yên nặng',
        'Diabetes insipidus differential'           => 'Đái nhạt (cần phân biệt)',
        'Growth hormone deficiency'                 => 'Thiếu hụt hormone tăng trưởng',
        'Growth retardation in children'            => 'Chậm tăng trưởng ở trẻ em',
        'Constitutional short stature'              => 'Thấp lùn thể trạng',
        'Carcinoid tumor'                           => 'U carcinoid',

        // === PHỤ KHOA / SINH SẢN ===
        'PMS'                                       => 'Hội chứng tiền kinh nguyệt (PMS)',
        'PMS with fatigue and mood changes'         => 'Hội chứng tiền kinh nguyệt kèm mệt mỏi và thay đổi tâm trạng',
        'PMS with mood changes'                     => 'Hội chứng tiền kinh nguyệt kèm thay đổi tâm trạng',
        'Dysmenorrhea'                              => 'Đau bụng kinh',
        'Dysmenorrhea (cold type)'                  => 'Đau bụng kinh thể hàn',
        'Primary dysmenorrhea'                      => 'Đau bụng kinh nguyên phát',
        'Primary/secondary dysmenorrhea'            => 'Đau bụng kinh nguyên/thứ phát',
        'Endometriosis'                             => 'Lạc nội mạc tử cung',
        'Adenomyosis'                               => 'Nội mạc tử cung trong cơ',
        'Uterine fibroids'                          => 'U xơ tử cung',
        'Uterine fibroids with anemia'              => 'U xơ tử cung kèm thiếu máu',
        'Uterine prolapse'                          => 'Sa tử cung',
        'Dysfunctional uterine bleeding'            => 'Rối loạn kinh nguyệt cơ năng',
        'Oligomenorrhea'                            => 'Kinh ít/thưa',
        'Chronic pelvic pain'                       => 'Đau vùng chậu mạn tính',
        'Pelvic inflammatory disease'               => 'Viêm vùng chậu',
        'PCOS'                                      => 'Hội chứng buồng trứng đa nang (PCOS)',
        'Ovarian cysts'                             => 'Nang buồng trứng',
        'Premature ovarian failure'                 => 'Suy buồng trứng sớm',
        'Premature ovarian insufficiency'           => 'Suy buồng trứng sớm',
        'Infertility'                               => 'Vô sinh',
        'Menopause'                                 => 'Mãn kinh',
        'Menopausal syndrome'                       => 'Hội chứng mãn kinh',
        'Menopausal hot flashes severe'             => 'Bốc hỏa mãn kinh nặng',
        'Menopause syndrome complex'                => 'Hội chứng mãn kinh phức tạp',
        'Perimenopausal syndrome'                   => 'Hội chứng tiền mãn kinh',
        'Recurrent vaginal discharge'               => 'Khí hư âm đạo tái phát',
        'Vulvovaginitis'                            => 'Viêm âm hộ-âm đạo',
        'STI'                                       => 'Bệnh lây qua đường tình dục (STI)',
        'Postpartum blood loss'                     => 'Mất máu sau sinh',
        'Postpartum conditions'                     => 'Các vấn đề sau sinh',
        'Post-partum deficiency'                    => 'Suy nhược sau sinh',
        'Eclampsia'                                 => 'Sản giật',

        // === NAM KHOA ===
        'Male infertility'                          => 'Vô sinh nam',
        'Male hypogonadism'                         => 'Thiểu năng sinh dục nam',
        'Male sexual dysfunction'                   => 'Rối loạn chức năng tình dục nam',
        'Premature ejaculation'                     => 'Xuất tinh sớm',
        'Premature ejaculation with insomnia'       => 'Xuất tinh sớm kèm mất ngủ',
        'Nocturnal emission disorder'               => 'Rối loạn xuất tinh ban đêm',
        'Spermatorrhea'                             => 'Di tinh',
        'Sexual dysfunction with hypersexuality'    => 'Rối loạn tình dục kèm cường dâm',
        'Sexual neurasthenia'                       => 'Suy nhược tình dục',
        'Andropause'                                => 'Mãn dục nam (Andropause)',
        'Varicocele'                                => 'Giãn tĩnh mạch tinh hoàn',
        'Epididymo-orchitis (non-infective)'        => 'Viêm mào tinh-tinh hoàn (không nhiễm khuẩn)',
        'Chronic scrotal pain'                      => 'Đau bìu mạn tính',
        'Scrotal eczema'                            => 'Eczema bìu',

        // === MÁU / MIỄN DỊCH ===
        'Anemia'                                    => 'Thiếu máu',
        'Anemia mild'                               => 'Thiếu máu nhẹ',
        'Anemia iron deficiency'                    => 'Thiếu máu thiếu sắt',
        'Iron deficiency anemia'                    => 'Thiếu máu thiếu sắt',
        'Iron-deficiency anemia'                    => 'Thiếu máu thiếu sắt',
        'Iron-deficiency anemia with GI symptoms'   => 'Thiếu máu thiếu sắt kèm triệu chứng tiêu hóa',
        'Anemia with thrombotic tendency'           => 'Thiếu máu kèm xu hướng huyết khối',
        'Aplastic anemia'                           => 'Thiếu máu bất sản',
        'Chronic blood loss'                        => 'Mất máu mạn tính',
        'Post-hemorrhagic anemia'                   => 'Thiếu máu sau xuất huyết',
        'Chronic disease anemia'                    => 'Thiếu máu bệnh mạn tính',
        'ITP (Idiopathic thrombocytopenic purpura)' => 'Xuất huyết giảm tiểu cầu miễn dịch (ITP)',
        'ITP (immune thrombocytopenic purpura)'     => 'Xuất huyết giảm tiểu cầu miễn dịch (ITP)',
        'Sepsis with coagulopathy'                  => 'Nhiễm khuẩn huyết kèm rối loạn đông máu',
        'Sepsis with seizures'                      => 'Nhiễm khuẩn huyết kèm co giật',
        'Dengue hemorrhagic fever'                  => 'Sốt xuất huyết dengue',
        'Epistaxis'                                 => 'Chảy máu mũi',
        'Lymphadenopathy'                           => 'Hạch bạch huyết to',
        'Lymphedema'                                => 'Phù bạch huyết',
        'IgA deficiency'                            => 'Thiếu hụt IgA',
        'Primary immunodeficiency (mild)'           => 'Suy giảm miễn dịch nguyên phát (nhẹ)',
        'Recurrent aphthous ulcers'                 => 'Loét miệng áp-tơ tái phát',
        'Oral ulcers aphthous'                      => 'Loét miệng áp-tơ',
        'Gingivitis'                                => 'Viêm lợi',
        'Herpes labialis'                           => 'Herpes môi',
        'Herpes zoster'                             => 'Zona (Herpes zoster)',
        'Sjogren syndrome (mild)'                   => 'Hội chứng Sjögren nhẹ',
        'Sjögren syndrome GI involvement'           => 'Hội chứng Sjögren có biểu hiện tiêu hóa',
        "Sjögren's syndrome pulmonary"              => 'Hội chứng Sjögren ở phổi',
        "Sjögren's with lung involvement"           => 'Hội chứng Sjögren kèm biểu hiện phổi',
        'Cold urticaria'                            => 'Mề đay lạnh',
        'Eczema (weeping)'                          => 'Chàm da (rỉ dịch)',
        'Lipomas'                                   => 'U mỡ',
        'Benign tumors'                             => 'U lành tính',

        // === MỆT MỎI / SUY NHƯỢC ===
        'Chronic fatigue'                           => 'Mệt mỏi mạn tính',
        'Chronic fatigue syndrome'                  => 'Hội chứng mệt mỏi mạn tính',
        'Chronic fatigue syndrome (ME/CFS)'         => 'Hội chứng mệt mỏi mạn tính (ME/CFS)',
        'Post-illness fatigue'                      => 'Mệt mỏi sau bệnh',
        'Post-viral fatigue'                        => 'Mệt mỏi sau nhiễm virus',
        'Post-chemotherapy fatigue'                 => 'Mệt mỏi sau hóa trị',
        'Post-radiotherapy syndrome'                => 'Hội chứng sau xạ trị',
        'Post-radiation proctitis chronic'          => 'Viêm trực tràng mạn tính sau xạ trị',
        'Post-chemotherapy digestive impairment'    => 'Suy giảm tiêu hóa sau hóa trị',
        'General debility'                          => 'Suy nhược toàn thân',
        'Post-surgical debility'                    => 'Suy nhược sau phẫu thuật',
        'Convalescence'                             => 'Giai đoạn hồi phục sau bệnh',
        'Adrenal fatigue'                           => 'Mệt mỏi tuyến thượng thận',
        'Advanced aging'                            => 'Lão hóa tiến triển',
        'Premature aging'                           => 'Lão hóa sớm',

        // === TAI / MŨI / HỌNG / MẮT ===
        'Tinnitus chronic'                          => 'Ù tai mạn tính',
        'Age-related sensorineural hearing loss (presbycusis)' => 'Nghe kém thần kinh giác quan theo tuổi',
        'Noise-induced hearing loss chronic'        => 'Nghe kém do tiếng ồn mạn tính',
        'Age-related macular degeneration'          => 'Thoái hóa điểm vàng tuổi già',
        'Acute glaucoma'                            => 'Tăng nhãn áp cấp (Glaucoma)',

        // === DA LIỄU ===
        'Eczema (weeping)'                          => 'Chàm da (rỉ dịch)',
        'Scrotal eczema'                            => 'Chàm bìu',
        'Psoriasis'                                 => 'Vẩy nến',

        // === KHÁC / PHỨC HỢP ===
        'Inguinal hernia'                           => 'Thoát vị bẹn',
        'Turner syndrome'                           => 'Hội chứng Turner',
    ];
}
